=== klug0xy/directorymanage/directorymanage/resources/directoryManagerDbTest.dtd
<!ELEMENT dataset (
    Groupe*,
    Person*,
PersonsTokens*,
User_roles*)>

<!ELEMENT Groupe EMPTY>
<!ATTLIST Groupe
    id CDATA #REQUIRED
    name CDATA #REQUIRED
>

<!ELEMENT Person EMPTY>
<!ATTLIST Person
    id CDATA #REQUIRED
    firstName CDATA #REQUIRED
    lastName CDATA #REQUIRED
mail CDATA #REQUIRED
website CDATA #REQUIRED
    birthday CDATA #REQUIRED
    password CDATA #REQUIRED
    groupId CDATA #IMPLIED
enabled CDATA #REQUIRED
>

<!ELEMENT PersonsTokens EMPTY>
<!ATTLIST PersonsTokens
    id CDATA #REQUIRED
    personId CDATA #REQUIRED
token CDATA #REQUIRED
expiryDate CDATA #REQUIRED
>

<!ELEMENT User_roles EMPTY>
<!ATTLIST User_roles
    username CDATA #REQUIRED
    role CDATA #REQUIRED
>

=== klug0xy/directorymanage/directorymanage/src/test/resources/directoryManagerDbTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "directoryManagerDbTest.dtd">
<dataset>
  <Groupe id="1" name="M2-ISL"/>
  <Groupe id="2" name="M2-FSI"/>
  <Groupe id="3" name="M2-ID"/>
  <Groupe id="4" name="M2-SIR"/>
  <Person id="1" firstName="Houssem" lastName="Mjid" mail="mjidhoussem@gmail.com" website="www.jdid.fr" birthday="1993-07-30" password="$2a$10$W9oRWeFmOT0bByL5fmAceucetmEYFg2yzq3e50mcu.CO7rUDb/poG" groupId="1" enabled="1"/>
  <Person id="2" firstName="Hichem" lastName="Bouhlel" mail="madridinho123@gmail.com" website="www.bouhlel.tk" birthday="1993-06-26" password="$2a$10$neO/1E39cKzp4D5komsCbuqNlDtC3nsEu4qHy5P0oB7Ktj6qdUvpG" groupId="1" enabled="1"/>
 <Person id="3" firstName="Adem" lastName="Bekouche" mail="hous12256@hotmail.fr" website="www.jdid.fr" birthday="1993-01-01
" password="$2a$10$.YaJK/0CV.ouXe4VFo.UNuQqMn8FgkLnfjmaN1I6SUpi4UQNR7iDa" groupId="1" enabled="1"/>
<Person id="4" firstName="Oumaima" lastName="Nammassi" mail="namassi@gmail.fr" website="www.google.fr" birthday="1993-06-23
" password="$2a$10$H8TN7LEs2U1MmhHUfUMfV.ttRCiEtXG/4KU/cNnV3rsMJLyOxDuau" groupId="2" enabled="1"/>
<PersonsTokens id="2" personId="1" token="d6365f3a-8fa6-473c-8049-dad4b63cf131" expiryDate="2017-12-03"/>
<PersonsTokens id="3" personId="3" token="2bd7b60f-3d84-413e-9b25-055e07a37a0d" expiryDate="2017-12-06"/>
<PersonsTokens id="4" personId="2" token="16025466-6f51-4a3f-92ae-f238ef5d08b3" expiryDate="2017-12-07"/>
<User_roles username="hous12256@hotmail.fr" role="ROLE_USER"/>
<User_roles username="madridinho123@gmail.com" role="ROLE_USER"/>
<User_roles username="mjidhoussem@gmail.com" role="ROLE_ADMIN"/>
<User_roles username="namassi@gmail.fr" role="ROLE_USER"/>
<User_roles username="risch@value.fr" role="ROLE_USER"/>
</dataset>
