=== klug0xy/directorymanage/directorymanage/src/directoryManagerDbTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
          <!-- XML Schema Generated from XML Document on Thu Dec 07 2017 21:31:52 GMT+0100 (CET) -->
          <!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
       <xs:element name="dataset">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="Groupe" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:attribute name="id" type="xs:int"></xs:attribute>
                                          <xs:attribute name="name" type="xs:string"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="Person" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:attribute name="id" type="xs:int"></xs:attribute>
                                          <xs:attribute name="firstName" type="xs:string"></xs:attribute>
                                          <xs:attribute name="lastName" type="xs:string"></xs:attribute>
                                          <xs:attribute name="mail" type="xs:string"></xs:attribute>
                                          <xs:attribute name="website" type="xs:string"></xs:attribute>
                                          <xs:attribute name="birthday" type="xs:date"></xs:attribute>
                                          <xs:attribute name="password" type="xs:string"></xs:attribute>
                                          <xs:attribute name="groupId" type="xs:int"></xs:attribute>
                                          <xs:attribute name="enabled" type="xs:int"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="PersonsTokens" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:attribute name="id" type="xs:int"></xs:attribute>
                                          <xs:attribute name="personId" type="xs:int"></xs:attribute>
                                          <xs:attribute name="token" type="xs:string"></xs:attribute>
                                          <xs:attribute name="expiryDate" type="xs:date"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                            <xs:element name="User_roles" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:attribute name="username" type="xs:string"></xs:attribute>
                                          <xs:attribute name="role" type="xs:string"></xs:attribute>
                                      </xs:complexType>
                               </xs:element>
                        </xs:sequence>
                 </xs:complexType>
          </xs:element>
   </xs:schema>

=== klug0xy/directorymanage/directorymanage/src/setupRemovePerson.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--<!DOCTYPE dataset SYSTEM "/home/mjid/git/LocalDirectoryManage/directorymanage/src/directoryManagerDbTest.dtd">!-->
<dataset xsi:schemaLocation="directoryManagerDbTest.xsd">
<Groupe id="1" name="M2-ISL"/>
<Groupe id="2" name="M2-FSI"/>
  <Person id="1" firstName="Houssem" lastName="Mjid" mail="mjidhoussem@gmail.com" website="www.jdid.fr" birthday="1993-07-30" password="$2a$10$W9oRWeFmOT0bByL5fmAceucetmEYFg2yzq3e50mcu.CO7rUDb/poG" groupId="1" enabled="1"/>
  <Person id="2" firstName="Hichem" lastName="Bouhlel" mail="madridinho123@gmail.com" website="www.bouhlel.tk" birthday="1993-06-26" password="$2a$10$neO/1E39cKzp4D5komsCbuqNlDtC3nsEu4qHy5P0oB7Ktj6qdUvpG" groupId="1" enabled="1"/>
 <Person id="3" firstName="Adem" lastName="Bekouche" mail="hous12256@hotmail.fr" website="www.jdid.fr" birthday="1993-01-01" password="$2a$10$.YaJK/0CV.ouXe4VFo.UNuQqMn8FgkLnfjmaN1I6SUpi4UQNR7iDa" groupId="1" enabled="1"/>
<Person id="4" firstName="Oumaima" lastName="Nammassi" mail="namassi@gmail.fr" website="www.google.fr" birthday="1993-06-23" password="$2a$10$H8TN7LEs2U1MmhHUfUMfV.ttRCiEtXG/4KU/cNnV3rsMJLyOxDuau" groupId="2" enabled="1"/>
<Person id="5" firstName="Philip" lastName="Risch" mail="risch@value.fr" website="www.risch.fr" birthday="1993-09-30" password="$2a$10$H8TN7LEs2U1MmhHUfUMfV.ttRCiEtXG/4KU/cNnV3rsMJLyOxDuau" groupId="2" enabled="1"/>
<PersonsTokens id="2" personId="1" token="d6365f3a-8fa6-473c-8049-dad4b63cf131" expiryDate="2017-12-03"/>
<User_roles username="hous12256@hotmail.fr" role="ROLE_USER"/>
</dataset>
